[build]
  publish = "."
  functions = "netlify/functions"

# Basic redirects for clean URLs
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  force = false
  conditions = {Path = ["!**.html", "!**.css", "!**.js", "!**.jpg", "!**.png", "!**.webp", "!**.svg", "!**.ico"]}

# For URLs with query parameters
[[redirects]]
  from = "/*?*"
  to = "/:splat.html?:query"
  status = 200
  force = false
  conditions = {Path = ["!**.html", "!**.css", "!**.js", "!**.jpg", "!**.png", "!**.webp", "!**.svg", "!**.ico"]}

# Catch-all redirect as fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  